// src/src/components/footera.tsx
import { FunctionalComponent } from 'preact'

const FooterA: FunctionalComponent = () => {
  return (
    <div className="container glass center">
      <a
        target="_blank"
        className="btn btn-secondary"
        href="https://github.com/liukonen"
        role="button"
        rel="noreferrer"
        aria-label="Github"
        data-toggle="tooltip"
        data-placement="top"
        title="GitHub"
      >
        <i className="bi bi-github"></i> GitHub
      </a>

      <a
        target="_blank"
        className="btn btn-primary bg-lnkdin"
        href="https://www.linkedin.com/in/lukeliukonen/"
        role="button"
        rel="noreferrer"
        aria-label="LinkedIn"
        data-toggle="tooltip"
        data-placement="top"
        title="LinkedIn"
      >
        <i className="bi bi-linkedin"></i> LinkedIn
      </a>

      <a
        className="btn btn-danger"
        href="mailto:liukonen@gmail.com?subject=GitHub_Home_Page"
        role="button"
        rel="noreferrer"
        aria-label="email"
        data-toggle="tooltip"
        data-placement="top"
        title="email"
      >
        <i className="bi bi-envelope-fill"></i> Email
      </a>

      <a
        target="_blank"
        className="btn btn-light"
        href="https://dev.to/liukonen"
        role="button"
        rel="noreferrer"
        aria-label="dev To"
        data-toggle="tooltip"
        data-placement="top"
        title="DEV Community"
      >
        <i className="bi bi-file-code-fill"></i> DEV Community
      </a>
    </div>
  )
}

export default FooterA

// src/src/lib/footerA.svelte
<div class="container glass center">
    <a target="_blank" class="btn btn-secondary" href="https://github.com/liukonen" role="button" rel="noreferrer" aria-label="Github" data-toggle="tooltip" data-placement="top" title="GitHub"><i class="bi bi-github"></i> GitHub</a>
    <a target="_blank" class="btn btn-primary bg-lnkdin" href="https://www.linkedin.com/in/lukeliukonen/" role="button" rel="noreferrer" aria-label="LinkedIn" data-toggle="tooltip" data-placement="top" title="LinkedIn"><i class="bi bi-linkedin"></i> LinkedIn</a>
    <a class="btn btn-danger" href="mailto:liukonen@gmail.com?subject=GitHub_Home_Page" role="button" rel="noreferrer" aria-label="email" data-toggle="tooltip" data-placement="top" title="email"><i class="bi bi-envelope-fill"> Email</i></a>
    <a target="_blank" class="btn btn-light" href="https://dev.to/liukonen" role="button" rel="noreferrer" aria-label="dev To"><i class="bi bi-file-code-fill"></i> DEV Community</a>
</div>

<style lang="sass">
.center
  text-align: center
  align-content: center
</style>
